### ISSUE TITLE
Add recommended python version in README

### ISSUE THREAD

**Issue by EthanS94** [cinemascience/pycinema#3]
@dhrogers 

I am using an older python, 3.6.9, and tried following the [Creating a local python environment for the workbench](https://github.com/cinemascience/pycinema#creating-a-local-python-environment-for-the-workbench) instructions.

I got an error when installing `scipy` in the venv:

```
RuntimeError: Python version >= 3.8 required.
```

I think the recommended python version should be specified in the instructions to help avoid install issues.

**Comment by dhrogers** [comment]
Hi, Ethan -

For the project with Quincy, we should use the cinemasci module. The pycinema stuff will hit a bunch of requirements that the HPC systems aren't going to support yet.

Thanks for the note ... I will put that in the instructions.

- David
________________________________________
From: Ethan Stam ***@***.***>
Sent: Tuesday, January 31, 2023 4:09 PM
To: cinemascience/pycinema
Cc: Rogers, David Honegger; Mention
Subject: [EXTERNAL] [cinemascience/pycinema] Add recommended python version in README (Issue #3)

@dhrogers<https://urldefense.com/v3/__https://github.com/dhrogers__;!!Bt8fGhp8LhKGRg!F73W0UwSJxdpDHimEa4IRUGdQlxE4cLg8EbVm0cqXZOCwQqG6qy97nMu0U7kO-4opmJiQUZLbRPhG5FSXFTJug$>

I am using an older python, 3.6.9, and tried following the Creating a local python environment for the workbench<https://urldefense.com/v3/__https://github.com/cinemascience/pycinema*creating-a-local-python-environment-for-the-workbench__;Iw!!Bt8fGhp8LhKGRg!F73W0UwSJxdpDHimEa4IRUGdQlxE4cLg8EbVm0cqXZOCwQqG6qy97nMu0U7kO-4opmJiQUZLbRPhG5HG2xDmLA$> instructions.

I got an error when installing scipy in the venv:

RuntimeError: Python version >= 3.8 required.


I think the recommended python version should be specified in the instructions to help avoid install issues.

**Comment by dhrogers** [comment]
N/A
